<?php foreach ($posts as $post): ?>
    <div>
        <a href="/post/<?= $post['id'] ?>"><?= $post['name'] ?></a>
        <form action="/post/<?= $post['id'] ?>" method="post">
            <input type="hidden" name="_METHOD" value="DELETE">
            <input type="submit" value="DELETE">
        </form>
    </div>
<?php endforeach; ?>
<? if ($prevPageUrl): ?>
    <a href="<?= $prevPageUrl ?>">назад</a>
<? endif ?>
<? if ($nextPageUrl): ?>
    <a href="<?= $nextPageUrl ?>">вперед</a>
<? endif ?>
