<a href="/courses">/courses</a>
<form action="/courses" method="post">
    <div>
        <label>
            имя курса
            <input type="text" name="course[title]" value="<?= htmlspecialchars($course['title']) ?>">
        </label>
        <?php if (isset($errors['title'])): ?>
            <div><?= $errors['title'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            платность курса
            <select name="course[paid]">
                <option value="true" <?= $course['paid'] === 'true' ? 'selected' : '' ?>>Да</option>
                <option value="false" <?= $course['paid'] === 'false' ? 'selected' : '' ?>>Нет</option>
            </select>
        </label>
        <?php if (isset($errors['paid'])): ?>
            <div><?= $errors['paid'] ?></div>
        <?php endif ?>
    </div>

    <input type="submit" value="Send">
</form>