<a href="/users">Все Пользователи</a>
<!-- BEGIN (write your solution here) -->
<form action="">
    <input type="text" name="term" value="<?= $term ?>" placeholder="filter by firstname">
    <input type="submit" value="FILTER">
</form>
<? if (!empty($users)): ?>
    <table border="1">
        <thead>
        <tr>
            <th>id</th>
            <th>firstName</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?= $user['id'] ?></td>
                <td><a href="/users/<?= $user['id'] ?>"><?= $user['firstName'] ?></a></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<? endif ?>
<!-- END -->
